### ISSUE TITLE
Feature Request: Make ACL configurable

### ISSUE THREAD

**Issue by narektutikian** [midudev/s3-folder-upload#15]
I noticed that the ACL in upload config is hardcoded `ACL: 'public-read'`. 

I need the uploaded files to have configurable ACL.

Please make this configurable.

**Comment by midudev** [comment]
Hey! I've published version 2.3.0 with the possibility of changing the value of ACL for all the uploads and at file level. :)

Could you test it @narek-king and tell me if it's working? :)

**Comment by narektutikian** [comment]
Thanks a lot. I will give it a try.
