### ISSUE TITLE
Feature Request: Make the folder name the name of the folder you're uploading.

### ISSUE THREAD

**Issue by JLee21** [midudev/s3-folder-upload#2]
I noticed that if the folder you are uploading to S3 is not within the path, the name of the folder defaults to `other`.

The feature request would be to simply parse the given folder path input  in order to grab the folder name.

E.g.
If I run: `s3folderUpload('path/to/myFolder', credentials)`
the folder name that is created on s3 would be `myFolder` and not `other`.

**Comment by midudev** [comment]
HI @JLee21, with the latest changes you could be able to achieve what you want: https://github.com/midudev/s3-folder-upload#options

If you disable the `folderByType` and use the `uploadFolder` option, then you'll be able to achieve what you're looking for.

**Comment by masum-mollik-rocketml** [comment]
I am using following option:
```
const options = {
  useFoldersForFileTypes: false,
  useIAMRoleCredentials: false,
  uploadFolder: 'test-reports',
  folderByType: false
}
```
But still facing this issue
