### ISSUE TITLE
useIAMRoleCredentials does not seem working in CLI mode

### ISSUE THREAD

**Issue by danil-smirnov** [midudev/s3-folder-upload#4]
Has `useIAMRoleCredentials` option been carefully tested?

I didn't manage to make it working. Credentials from IAM role are attached and available if checking with curl:
```
curl http://169.254.169.254/latest/meta-data/iam/security-credentials/my_role
... creds ...
```

But if I run the task using npx:
```
npx s3-folder-upload test --region=eu-west-1 --bucket=my.bucket --useIAMRoleCredentials=true --uploadFolder=test/1234567
```
I keep getting error:
```
root/aws-credentials.json
[warn] Impossible load credentials from /root/aws-credentials.json
[error] Invalid credentials
```

**Comment by midudev** [comment]
I'll take a look on this asap and I'll be back to you! Thx!

**Comment by danil-smirnov** [comment]
Hey @midudev , I've investigated a bit and discovered [these lines](https://github.com/midudev/s3-folder-upload/blob/master/lib/aws-credentials.js#L44-L45) in which you returned `undefined` for AWS credentials which I believe is a bug, as you should keep `bucket` and `region` parameters there.

I suppose you also should add 'useIAMRoleCredentials' item into [this list](https://github.com/midudev/s3-folder-upload/blob/master/lib/build-cli-parameters.js#L11).

**Comment by midudev** [comment]
Beta 2.0.5 has been published. Could you test it in order to be sure the problem is gone? Thanks!

The PR with the fix: https://github.com/midudev/s3-folder-upload/pull/5

**Comment by abohannon** [comment]
@midudev I've installed the beta and am still getting the same error.

```
[error] Required missing fields: accessKeyId
[error] Required missing fields: accessKeyId, bucket, region, secretAccessKey
[warn] Impossible load credentials from /Users/adambohannon/Projects/back-up-contentful/aws-credentials.json
(node:81170) UnhandledPromiseRejectionWarning: Error: Invalid credentials
```

In my handler:

```
const credentials = {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: process.env.AWS_REGION,
    bucket: process.env.AWS_S3_BUCKET_NAME
  };
  console.log("Uploading directory to s3...");
  const response = await s3FolderUpload(exportDir, credentials);

  console.log("RESPONSE", response);
```

**Comment by midudev** [comment]
Hey @abohannon. Thanks for your input. Could you add a `console.log(process.env.AWS_ACCESS_KEY_ID)` before calling `s3FolderUpload` and tell me if there's any value? It seems weird as your use case is tested here: https://github.com/midudev/s3-folder-upload/blob/master/test/lib/aws-credentials-Test.js#L8 and should be working as expected.

**Comment by midudev** [comment]
`2.1.0` published  fixing this.
