### ISSUE TITLE
Async / Callback

### ISSUE THREAD

**Issue by wpdas** [midudev/s3-folder-upload#6]
Hi, Can you may implement an async/callback way of doing this job?

**Comment by midudev** [comment]
Working on it. :)

**Comment by midudev** [comment]
`2.1.0` published, should have support for promises now. :)

**Comment by Allain55** [comment]
Hi, I couldn't find a way to detect once the uploading is completed/error happened. Could you return the uploadDirectory method's return value inside the default export so it can be used outside?

**Comment by midudev** [comment]
@Allain55 Check this out: https://github.com/midudev/s3-folder-upload/pull/8/files

**Comment by Allain55** [comment]
Nice, thank you!
